WIP Normalize development section folders
flyve-mdm/flyve-mdm-android-dashboard pull request #55
Opened 2018-06-18 13:53 UTC by Naylin15

### Changes description
Rename the folders for development section on gh-pages
Add license headers
Review doc-blocks
Modify workflow to add changelog when there is a merge into master

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Closes #N/A

2018-06-19 21:47 UTC, Naylin15 commented
- There aren't being created unnecesary commits to develop branch
- Added new scripts to improve validation process and avoid premature and false failures, in order to keep the build status in green (readme)
- Made several tests to implement the changes

2018-06-20 20:45 UTC, Naylin15 commented
I've been having an issue with the validation on master branch, it enters a loop and creates release after release

2018-06-20 22:03 UTC, Naylin15 commented
Still making tests to solve the validation issue

2018-06-21 13:29 UTC, ajsb85 requested changes

2018-06-21 13:29 UTC, ajsb85 commented on ci/scripts/ci_changelog.sh
> +#  Flyve MDM Agent for Android is a subproject of Flyve MDM. Flyve MDM is a mobile
Dashboard

2018-06-21 15:20 UTC, Naylin15 commented
Fixed the validation issue

2018-06-21 21:03 UTC, Naylin15 commented
I've been having issues while sending the documentation to gh-pages

2018-06-21 21:45 UTC, Naylin15 commented
The issues are being caused due to npm

2018-06-22 21:20 UTC, Naylin15 commented
With yarn I avoid all previous issues

However, after running the documentation scripts, by some reason it turns unavailable the devdependencies, it throws a command not found

2018-06-25 19:50 UTC, Naylin15 commented
I think the issue was generated due to the change of branch to update the styles for the coverage and test-reports before

I'm trying to solve this by creating two new scripts

The first will generate coverage, code documentation and send them to gh-pages

The second will update headers and styles for the development folder

This is to make sure the execution of one script do not affect the other

2018-06-25 22:11 UTC, Naylin15 commented
There is no longer an issue with the permissions and the documentation for the development section is being created and sent as it should

2018-06-26 09:24 UTC, ajsb85 submitted a review, later dismissed

2018-06-26 22:46 UTC, ajsb85 submitted a review, later dismissed

2018-06-27 13:42 UTC, Naylin15 commented
Hi, @ajsb85 @rafaelje 

The PR is finished, this is how the new workflow will be:

### On feature branch

- run Build
- run Test Api v16

### On develop

There are two main scripts which include the commit validation to avoid repeated workflows, and contain the scripts related to their process.

- Setup environment (ci_setup.sh)
- Deploy Beta (ci_deploy_beta.sh)
  - Update version and code (ci_updateversion.sh)
  - Create about information (ci_about.sh)
  - Transifex for translations (ci_transifex.sh)
  - Create APK
  - Deploy to Google Play Beta version (ci_fastlane.sh)
- Documentation (ci_documentation.sh)
  - Create Coverage, Test reports and Code Documentation (ci_generate_documentation.sh)
  - Update headers and styles for proper display on project site
- Update screenshots (ci_screenshots.sh)

### On master

There is one main script that includes the commit validation to avoid repeated workflows, and contains the scripts related to the process.

- Setup environment (ci_setup.sh)
- Deploy Production (ci_deploy_production.sh)
  - Update version and code, generate Changelog (ci_updateversion.sh)
  - Create about information (ci_about.sh)
  - Transifex for translations (ci_transifex.sh)
  - Create APK
  - Push new tags and update develop branch (ci_push_changes.sh)
  - Deploy to Google Play (ci_fastlane.sh)
  - Create a GitHub release (ci_github_release.sh)


## Note:

I moved the validation because in the old workflow it gave false errors, when actually the build was successful

Some scripts were removed since the use of the gh-pages library simplified the process and were no longer necessary

On develop branch there will be no commits when making merge with it, but it will be updated the android code and about properties, and only the documentation and the screenshots will be generated - updated

On master branch there will be commits regarding the changelog, the update on Android Manifest values and about

Also, I'll [set up this project on Circle CI](https://circleci.com/add-projects/gh/flyve-mdm) with the variables from the android-mdm-agent and the GITHUB_EMAIL from #56 

![captura de pantalla 2018-06-27 a la s 9 34 51 a m](https://user-images.githubusercontent.com/30867977/41977551-9c39239c-79ed-11e8-8338-cb768d4766c6.png)

2018-06-27 13:50 UTC, rafaelje commented
@ajsb85 @Naylin15 made important changes and organize the CI scripts IMO please add your name on @author tag

2018-06-27 13:53 UTC, ajsb85 submitted a review, later dismissed

2018-07-20 21:31 UTC, ajsb85 approved these changes

2018-07-20 21:31 UTC, merged